name: AWS Assume Role

on: push

jobs:
  aws-assume-role:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Assume Role
        uses: docker://abatilo/aws-assume-role-action:v1.0.0
        env:
          ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          ROLE_SESSION_NAME: testing
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DURATION_SECONDS: 120
          
      - name: Identity Check
        run: |
          aws sts get-caller-identity

      - name: Show S3 Bucket List
        run: |
          aws s3 ls
